### ISSUE TITLE
1.0E-4 XRB instead of 0.0001 NANO

### ISSUE THREAD

**Issue by shamo42** [brainblocks/brainblocks-android#1]
First of all thank you for your amazing work.

- 1.0E-4 is not user friendly IMO
- The amount to pay text is a bit hidden in the upper left corner. The font is kind of small even on my 6.4 inch device
- Still using XRB & Raiblocks instead of NANO & Nano

edit: title should say: instead of 0.0001 NANO

**Comment by alexmok** [comment]
Thanks for this, it should be fixed now. Font size increased by 20% and logo is now rebranded.
