### ISSUE TITLE
Window disappears on configuration changes

### ISSUE THREAD

**Issue by shamo42** [brainblocks/brainblocks-android#2]
The payment window is lost on configuration changes (like screen rotation).

**Comment by alexmok** [comment]
Good catch! This fix is a bit tougher than I thought. I switched to using DialogFragments instead of just AlertDialogs but that brought some new problems. I'll give you an update as soon as I can.

**Comment by alexmok** [comment]
Hey, it should be fixed now. Try v1.3. There is also a bit of extra code you have to add to your activity. I've updated the readme file.  

I noticed that when the orientation changes, the timer shows 120 seconds remaining until the next tick, then it changes back to what it was supposed to be. I couldn't figure out how to fix that yet, but it's pretty minor. I just wanted to get this fix out first, I'll create a new issue for this bug.
